### ISSUE TITLE
[FEATURE] Add Stockfish 14 to ranking list

### ISSUE THREAD

**Issue by Virinas-code** [vibranium21/chess-engines-mania#1]
Recently Stockfish 14 was published, but there is no Stockfish 14 rating in project.

**Comment by vibranium21** [comment]
This has been done

**Comment by Virinas-code** [comment]
Thanks !

**Comment by vibranium21** [comment]
http://www.computerchess.org.uk/ccrl/404/ Go to here for more mania it’s  one of my sources

**Comment by Virinas-code** [comment]
Yes, thanks for the link.

Le dim. 11 juil. 2021 à 12:18, vibranium21 ***@***.***> a
écrit :
